version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/public
      - ./conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    networks:
      - nginxphp

  php:
    image: php:7.1.11-fpm-alpine
    volumes:
      - ./public:/public
    expose:
      - 9000
    networks:
      - nginxphp

networks:
  nginxphp: